"use client";
import { useState, useEffect, useRef, useCallback, useMemo } from "react";
import { BookOpen, Library, MessageCircle, Upload, FileText, ShieldCheck, Send, Check, X, RotateCcw, Download, Plus, LoaderCircle, ChevronDown, Lightbulb, Eye, Trash2, CheckCircle2, UserRound, Mic, Volume2, Square } from "lucide-react";
import { splitGuidance, type Guidance, type Section, type Session, type Citation } from "@/lib/guidance";
import { extractFile } from "@/lib/extract";
import { useVoice } from "@/lib/useVoice";

async function api<T>(path:string,options:RequestInit={}):Promise<T>{
  const result=await fetch(`/api/${path}`,options),data=await result.json() as T & {error?:string};
  if(!result.ok)throw new Error(data.error||"The request could not be completed. Please try again.");return data;
}
const json=(data:unknown)=>({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});
type WorkspaceData={admin:boolean;email:string;documents:Guidance[];aiConfigured:boolean};
function SourceText({section,quote}:{section:Section;quote:string}){if(!quote||!section.text.includes(quote))return <p className="source-text">{section.text}</p>;const i=section.text.indexOf(quote);return <p className="source-text">{section.text.slice(0,i)}<mark>{quote}</mark>{section.text.slice(i+quote.length)}</p>;}

export default function Workspace({onSignOut}:{onSignOut:()=>void}){
  const [data,setData]=useState<WorkspaceData|null>(null),[docs,setDocs]=useState<Guidance[]>([]),[selected,setSelected]=useState<Guidance|null>(null);
  const [view,setView]=useState<"learn"|"admin">("learn"),[session,setSession]=useState<Session|null>(null),[source,setSource]=useState(0),[quote,setQuote]=useState("");
  const [input,setInput]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[mobileTab,setMobileTab]=useState("coach");
  const [editor,setEditor]=useState(false),[editing,setEditing]=useState<Guidance|null>(null),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[text,setText]=useState(""),[file,setFile]=useState<File|null>(null),[extracting,setExtracting]=useState(false),[deleteTarget,setDeleteTarget]=useState<Guidance|null>(null),[restart,setRestart]=useState(false);
  const messagesEnd=useRef<HTMLDivElement>(null),fileInput=useRef<HTMLInputElement>(null),dialogRef=useRef<HTMLDialogElement>(null),confirmRef=useRef<HTMLDialogElement>(null),loadSequence=useRef(0),busyRef=useRef(false);
  const voice=useVoice(setInput,view==="learn"&&!!session&&!loading,busy);
  const published=useMemo(()=>docs.filter(d=>d.status==="published"),[docs]);
  const choose=useCallback(async (doc:Guidance)=>{
    voice.cancel();
    const seq=++loadSequence.current;setSelected(doc);setSource(0);setQuote("");setSession(null);setError("");setInput("");setMobileTab("coach");
    if(doc.status!=="published")return;
    setLoading(true);
    try{const result=await api<{session:Session}>("session",json({documentId:doc.id}));if(seq===loadSequence.current){setSession(result.session);setSource(result.session.step);}}
    catch(e){if(seq===loadSequence.current)setError((e as Error).message);}finally{if(seq===loadSequence.current)setLoading(false);}
  },[voice.cancel]);
  const refresh=useCallback(async (admin=false,keepId?:string)=>{
    const result=await api<WorkspaceData>(`workspace${admin?"?admin=1":""}`);setData(result);setDocs(result.documents);
    if(!admin){const doc=result.documents.find(d=>d.id===keepId)||result.documents.find(d=>!d.sample)||result.documents[0];if(doc)await choose(doc);else{setSelected(null);setSession(null);}}
    return result;
  },[choose]);
  useEffect(()=>{refresh().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[refresh]);
  useEffect(()=>{messagesEnd.current?.scrollIntoView({block:"nearest",behavior:"smooth"});},[session?.messages.length,busy]);
  useEffect(()=>{const dialog=dialogRef.current;if(editor&&!dialog?.open)dialog?.showModal();if(!editor&&dialog?.open)dialog.close();},[editor]);
  useEffect(()=>{const dialog=confirmRef.current;if((deleteTarget||restart)&&!dialog?.open)dialog?.showModal();if(!deleteTarget&&!restart&&dialog?.open)dialog.close();},[deleteTarget,restart]);
  const send=useCallback(async (message:string,step?:number)=>{
    if(!selected||!session||busyRef.current||voice.state.listening||!message.trim())return null;
    voice.cancel();
    busyRef.current=true;setBusy(true);setError("");
    try{const result=await api<{session:Session}>("coach",json({documentId:selected.id,version:selected.version,message:message.trim(),step:step??session.step}));setSession(result.session);setSource(result.session.step);setQuote("");setInput("");const reply=result.session.messages.at(-1);if(reply?.role==="assistant")voice.readNewReply([reply.content,reply.question].filter(Boolean).join("\n"));return result.session;}
    catch(e){setError((e as Error).message);throw e;}finally{busyRef.current=false;setBusy(false);}
  },[selected,session,voice.cancel,voice.readNewReply,voice.state.listening]);
  const safelySend=(message:string,step?:number)=>void send(message,step).catch(()=>{});
  const switchView=async(next:"learn"|"admin")=>{if(busy||extracting)return;voice.cancel();setView(next);setError("");setNotice("");setLoading(true);try{await refresh(next==="admin",selected?.id);}catch(e){setError((e as Error).message);}finally{setLoading(false);}};
  const openEditor=(doc:Guidance|null=null)=>{setEditing(doc);setTitle(doc?.title||"");setDescription(doc?.description||"");setText(doc?.content||"");setFile(null);setError("");setNotice("");setEditor(true);};
  const loadFile=async(chosen:File)=>{if(extracting)return;setExtracting(true);setError("");try{const content=await extractFile(chosen);setFile(chosen);setText(content);if(!title)setTitle(chosen.name.replace(/\.[^.]+$/,"").replace(/[-_]/g," "));}catch(e){setError((e as Error).message);}finally{setExtracting(false);if(fileInput.current)fileInput.current.value="";}};
  const save=async()=>{if(busyRef.current||extracting)return;busyRef.current=true;setBusy(true);setError("");try{
    let result:{document:Guidance};
    if(editing){result=await api(`guidance/${editing.id}`,{...json({title,description,content:text,version:editing.version}),method:"PATCH"});}
    else{const body=new FormData();body.set("title",title);body.set("description",description);body.set("content",text);if(file)body.set("file",file);result=await api("guidance",{method:"POST",body});}
    setEditor(false);setNotice(editing?"Guidance updated.":"Guidance saved as a draft. Publish it when you are ready.");await refresh(true);return result.document;
  }catch(e){setError((e as Error).message);}finally{busyRef.current=false;setBusy(false);}};
  const publish=async(doc:Guidance)=>{setBusy(true);setError("");try{await api(`guidance/${doc.id}`,{...json({status:doc.status==="published"?"draft":"published",version:doc.version}),method:"PATCH"});await refresh(true);setNotice(doc.status==="published"?"Guidance unpublished. It is now visible only in Admin.":"Guidance published. Learners can now work through it.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const confirmAction=async()=>{voice.cancel();setBusy(true);setError("");try{if(deleteTarget){await api(`guidance/${deleteTarget.id}`,{method:"DELETE"});setDeleteTarget(null);setNotice("Guidance deleted.");await refresh(true);}else if(restart&&selected){const result=await api<{session:Session}>("session",json({documentId:selected.id,reset:true}));setSession(result.session);setSource(0);setQuote("");setRestart(false);}}catch(e){setError((e as Error).message);setDeleteTarget(null);setRestart(false);}finally{setBusy(false);}};
  const showCitation=(citation:Citation)=>{if(!selected)return;voice.cancel();const i=selected.sections.findIndex(s=>s.id===citation.sectionId);if(i<0)return;setSource(i);setQuote(citation.quote);setMobileTab("source");};
  const current=selected?.sections[session?.step||0],sourceSection=selected?.sections[source];
  const latestReply=session?.messages.slice().reverse().find(m=>m.role==="assistant");
  const previewSections=useMemo(()=>text.trim()?splitGuidance(text):[],[text]);

  return <div className="app-shell">
    <a href="#main" className="skip-link">Skip to guidance workspace</a>
    <header className="topbar"><a className="brand" href="/"><span className="brand-mark"><BookOpen size={24}/></span><span>Guidance<span className="brand-light">Coach</span></span></a><nav aria-label="Main navigation"><button className={view==="learn"?"nav-active":""} onClick={()=>switchView("learn")} disabled={busy}><MessageCircle size={18}/>Learning workspace</button>{data?.admin&&<button className={view==="admin"?"nav-active":""} onClick={()=>switchView("admin")} disabled={busy}><ShieldCheck size={18}/>Admin</button>}</nav><button className="signout-button" onClick={()=>{voice.cancel();onSignOut();}} disabled={busy||extracting}>Sign out</button><span className="account-mark" title={data?.email||"Signed in"}><UserRound size={18}/></span></header>
    <main id="main">
    <div className="page-heading"><div><p className="eyebrow">{view==="admin"?"MANAGE YOUR GUIDANCE":"LEARNING WORKSPACE"}</p><h1>{view==="admin"?"Guidance library":"Work through your guidance"}</h1></div><span className="private-label"><ShieldCheck size={16}/>Your private workspace</span></div>
    {!editor&&error&&<div className="alert error" role="alert">{error}<button className="text-button" onClick={()=>{voice.cancel();setError("");setLoading(true);refresh(view==="admin",selected?.id).catch(e=>setError(e.message)).finally(()=>setLoading(false));}}>Reload workspace</button></div>}
    {notice&&<div className="alert success" role="status"><CheckCircle2 size={18}/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice("")}><X size={16}/></button></div>}
    {view==="admin"?<>
      <div className="admin-toolbar"><p>Upload, check and publish the guidance your learners will use.</p><button className="primary" onClick={()=>openEditor()}><Plus size={18}/>Add guidance</button></div>
      {loading?<div className="empty-state"><LoaderCircle className="spin"/>Loading your guidance…</div>:<div className="admin-grid">{docs.map(doc=><article className="guide-card" key={doc.id}><div className="card-top"><span className="file-icon"><FileText size={24}/></span><span className={`status-pill ${doc.status}`}>{doc.status==="published"?"Published":"Draft"}</span></div><h2>{doc.title}</h2><p>{doc.description||"No description added."}</p><div className="card-meta">{doc.format} · {doc.sections.length} sections · Version {doc.version}{doc.sample&&" · Sample"}</div><div className="card-actions"><button className="secondary" onClick={()=>openEditor(doc)} disabled={busy}><Eye size={16}/>Review & edit</button><button className={doc.status==="published"?"text-button":"primary small"} onClick={()=>publish(doc)} disabled={busy}>{doc.status==="published"?"Unpublish":"Publish"}</button>{!doc.sample&&<button className="icon-button delete-button" title="Delete guidance" aria-label={`Delete ${doc.title}`} onClick={()=>setDeleteTarget(doc)} disabled={busy}><Trash2 size={17}/></button>}</div></article>)}</div>}
    </>:<div className="workspace-grid">
      <aside className="library-panel" aria-label="Guidance library"><div className="panel-title"><Library size={19}/><h2>Available guidance</h2><span className="count">{published.length}</span></div><div className="guide-list">{published.map(doc=><button disabled={busy} key={doc.id} className={`guide-option ${selected?.id===doc.id?"selected":""}`} onClick={()=>choose(doc)}><span className="file-icon"><FileText size={20}/></span><span><strong>{doc.title}</strong><small>{doc.sample?"Sample guide":doc.format} · {doc.sections.length} sections</small></span>{selected?.id===doc.id&&<Check size={17}/>}</button>)}</div>
        {selected&&<div className="section-list"><p className="eyebrow">YOUR WALKTHROUGH</p><ol>{selected.sections.map((s,i)=><li key={s.id}><button disabled={busy||loading} className={i===(session?.step||0)?"current-step":""} onClick={()=>{voice.cancel();setSource(i);setQuote("");setMobileTab("source");}}><span className={`step-number ${i<(session?.step||0)?"visited":""}`}>{i<(session?.step||0)?<Check size={13}/>:i+1}</span><span>{s.title}</span></button></li>)}</ol><p className="small-note">Select a section to read it. Use the coach to work through it.</p></div>}
        {data?.admin&&<button className="add-guidance-link" onClick={()=>switchView("admin")}><Upload size={17}/>Manage guidance</button>}
      </aside>
      <div className="mobile-tabs" role="tablist" aria-label="Workspace view"><button role="tab" aria-selected={mobileTab==="coach"} onClick={()=>{voice.cancel();setMobileTab("coach");}}>Coach</button><button role="tab" aria-selected={mobileTab==="source"} onClick={()=>{voice.cancel();setMobileTab("source");}}>Guidance</button></div>
      <section className={`coach-panel ${mobileTab!=="coach"?"mobile-hidden":""}`} aria-label="Guidance coach"><div className="coach-heading"><span className="coach-avatar"><MessageCircle size={22}/></span><div><h2>Your guidance coach</h2><p>Learn the process. Practise each step.</p></div>{session&&<button className="icon-button" title="Restart walkthrough" aria-label="Restart walkthrough" disabled={busy||loading} onClick={()=>{voice.cancel();setRestart(true);}}><RotateCcw size={17}/></button>}</div>
        {selected&&current&&<div className="step-header"><div><span>Section {(session?.step||0)+1} of {selected.sections.length}</span><strong>{current.title}</strong></div><div className="progress-track" role="progressbar" aria-label="Current walkthrough section" aria-valuemin={0} aria-valuemax={selected.sections.length} aria-valuenow={(session?.step||0)+1}><span style={{width:`${((session?.step||0)+1)/selected.sections.length*100}%`}}/></div></div>}
        {selected&&session&&<div className="voice-toolbar" aria-label="Read aloud controls">
          <label className="voice-option"><input type="checkbox" checked={voice.autoRead} onChange={e=>voice.toggleAuto(e.target.checked)} disabled={!voice.state.outputSupported}/>Read replies aloud automatically</label>
          <div className="voice-buttons"><button className="secondary small" disabled={!latestReply||!voice.state.outputSupported||busy||loading} onClick={()=>voice.read([latestReply?.content,latestReply?.question].filter(Boolean).join("\n"))}><Volume2 size={16}/>Read reply</button><button className="secondary small" disabled={!voice.state.speaking} onClick={voice.stop}><Square size={14}/>Stop reading</button></div>
          <label className="voice-select">Voice<select aria-label="Reading voice" value={voice.voiceURI} onChange={e=>voice.selectVoice(e.target.value)} disabled={!voice.state.outputSupported}><option value="">Automatic English voice</option>{voice.voices.map(v=><option value={v.voiceURI} key={v.voiceURI}>{v.name} ({v.lang})</option>)}</select></label>
          {!voice.state.outputSupported&&<p className="voice-help">Read aloud is unavailable in this browser. You can still read the text.</p>}
        </div>}
        <div className="conversation" role="log" aria-live="polite" aria-label="Coaching conversation" aria-busy={busy}>
          {loading?<div className="empty-state"><LoaderCircle className="spin"/><p>Opening your guidance…</p></div>:!selected?<div className="empty-state"><BookOpen size={36}/><h2>No guidance published yet</h2><p>{data?.admin?"Add your guidance in Admin, review the text, then publish it here.":"Your administrator will publish guidance here when it is ready."}</p>{data?.admin&&<button className="primary" onClick={()=>switchView("admin")}>Open Admin</button>}</div>:!session?<div className="empty-state"><p>Your session could not be opened.</p><button className="secondary" onClick={()=>choose(selected)}>Try again</button></div>:<>
          {!session.messages.length&&<div className="welcome-message"><span className="eyebrow">LET'S WORK THROUGH IT</span><h3>{selected.title}</h3><p>I’ll help you understand the guidance, then practise applying it a step at a time. You can ask a question whenever you need to.</p>{selected.sample&&<p className="sample-note">This is a fictional sample guide. Upload your own guidance in Admin.</p>}<button className="primary" disabled={busy} onClick={()=>safelySend("Start a walkthrough of the current section. Explain what I need to do, then ask me one question about applying it.")}><MessageCircle size={18}/>Start walkthrough</button></div>}
          {session.messages.map((m,i)=><article key={`${m.at}-${i}`} className={`chat-message ${m.role}`}><div className="message-byline">{m.role==="assistant"?<><span className="tiny-coach"><BookOpen size={13}/></span>Guidance coach</>:"You"}</div><div className="message-content"><p>{m.content}</p>{m.question&&<div className="coach-question"><Lightbulb size={17}/><p>{m.question}</p></div>}{!!m.citations?.length&&<div className="citations">{m.citations.map((c,j)=><button key={j} onClick={()=>showCitation(c)}><BookOpen size={13}/>{selected.sections.find(s=>s.id===c.sectionId)?.title||c.sectionId}</button>)}</div>}</div></article>)}
          {busy&&<div className="thinking"><LoaderCircle size={16} className="spin"/>Checking your guidance…</div>}<div ref={messagesEnd}/></>}
        </div>
        {selected&&session&&<div className="composer-area">{session.messages.length>0&&<div className="coach-actions"><button disabled={busy||loading||voice.state.listening} onClick={()=>safelySend("Explain this current section more simply and stay with this step.")}>Explain simply</button><button disabled={busy||loading||voice.state.listening} onClick={()=>safelySend("Give me a clearly labelled fictional practice example for this current section.")}>Give an example</button><button className="continue-button" disabled={busy||loading||voice.state.listening} onClick={()=>safelySend((session.step+1<selected.sections.length)?"Take me through the next section. Explain the actions I need to take and ask one application question.":"Review the current section and help me check whether I understand how to use it.",Math.min(session.step+1,selected.sections.length-1))}>{session.step+1<selected.sections.length?"Next section":"Review final section"}</button></div>}
          <div className="dictation-controls"><button className={`secondary small ${voice.state.listening?"listening":""}`} type="button" aria-pressed={voice.state.listening} disabled={!voice.state.inputSupported||busy||loading||voice.state.stopping} onClick={()=>voice.talk(input)}>{voice.state.listening?<Square size={14}/>:<Mic size={16}/>} {voice.state.stopping?"Finishing…":voice.state.listening?"Stop listening":"Talk"}</button><span>{voice.state.inputSupported?"Speak, check your words, then send.":"Voice input is unavailable here. Type your answer or use keyboard dictation."}</span></div>
          <p className={`voice-status ${voice.notice.error?"voice-error":""}`} role="status" aria-live="polite">{voice.notice.text||"Voice is optional. Your browser may use its speech service to process audio."}</p>
          <form onSubmit={e=>{e.preventDefault();safelySend(input);}}><label htmlFor="coach-message" className="sr-only">Your answer or question about the guidance</label><textarea id="coach-message" value={input} maxLength={1800} onChange={e=>setInput(e.target.value)} placeholder="Ask a question, or tell the coach what you would do…" disabled={busy||loading} readOnly={voice.state.listening} rows={2} onKeyDown={e=>{if(e.key==="Enter"&&(e.ctrlKey||e.metaKey)){e.preventDefault();safelySend(input);}}}/><button className="send-button" type="submit" disabled={!input.trim()||busy||loading||voice.state.listening} aria-label="Send your answer or question"><Send size={20}/></button></form><p className="composer-note"><BookOpen size={13}/>Check the linked source before using an answer in your work.</p></div>}
      </section>
      <aside className={`source-panel ${mobileTab!=="source"?"mobile-hidden":""}`} aria-label="Source guidance"><div className="panel-title"><BookOpen size={19}/><h2>The guidance</h2></div>{selected&&sourceSection?<><div className="source-selector"><label htmlFor="source-section">Read a section</label><div><select id="source-section" value={source} onChange={e=>{voice.cancel();setSource(Number(e.target.value));setQuote("");}}>{selected.sections.map((s,i)=><option key={s.id} value={i}>{i+1}. {s.title}</option>)}</select><ChevronDown size={15}/></div><button className="secondary small read-section" disabled={!voice.state.outputSupported||busy||loading} onClick={()=>voice.read(`${sourceSection.title}. ${sourceSection.text}`)}><Volume2 size={16}/>Read section</button>{voice.state.speaking&&<button className="secondary small read-section" onClick={voice.stop}><Square size={14}/>Stop reading</button>}</div><article className="source-document"><div className="source-meta">{selected.sample?"SAMPLE GUIDANCE":`${selected.format} GUIDANCE`} · V{selected.version}{sourceSection.page&&` · PAGE ${sourceSection.page}`}</div><h3>{sourceSection.title}</h3><SourceText section={sourceSection} quote={quote}/></article><div className="source-footer"><p>{selected.title}</p><a href={`/api/guidance/${selected.id}/original`}><Download size={15}/>Download original</a></div></>:<div className="empty-state"><FileText size={30}/><p>Choose a guide to read it here.</p></div>}</aside>
    </div>}
    </main>
    <footer className="site-footer"><span><BookOpen size={14}/>Guidance Coach</span><span>Answers grounded in your uploaded guidance</span></footer>
    <dialog ref={dialogRef} className="editor-dialog" onCancel={e=>{if(busy||extracting)e.preventDefault();else setEditor(false);}}><div className="dialog-heading"><div><p className="eyebrow">ADMIN</p><h2>{editing?"Review guidance":"Add guidance"}</h2></div><button className="icon-button" disabled={busy||extracting} onClick={()=>setEditor(false)} aria-label="Close guidance editor"><X size={22}/></button></div>
      {error&&<div className="alert error" role="alert">{error}</div>}
      {!editing&&<><div className={`upload-zone ${extracting?"extracting":""}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f&&!busy)void loadFile(f);}}><Upload size={26}/><strong>{extracting?"Reading your document…":file?file.name:"Upload a guidance document"}</strong><p>PDF, Word (.docx), TXT or Markdown · Up to 10 MB</p><button className="secondary" onClick={()=>fileInput.current?.click()} disabled={busy||extracting}>{extracting?<LoaderCircle size={16} className="spin"/>:<FileText size={16}/>}Choose a file</button><input ref={fileInput} type="file" accept=".pdf,.docx,.txt,.md" className="sr-only" onChange={e=>{const f=e.target.files?.[0];if(f)void loadFile(f);}}/><span className="small-note">You can also paste guidance into the text box below.</span></div></>}
      <label className="field-label" htmlFor="guide-title">Guidance title</label><input id="guide-title" value={title} maxLength={120} onChange={e=>setTitle(e.target.value)} placeholder="For example: Handling a change of address" disabled={busy}/><label className="field-label" htmlFor="guide-description">Short description <span>(optional)</span></label><input id="guide-description" value={description} maxLength={600} onChange={e=>setDescription(e.target.value)} placeholder="What will this guide help the learner do?" disabled={busy}/>
      <div className="text-review-heading"><label className="field-label" htmlFor="guidance-text">Check the guidance text</label><span>{previewSections.length} sections</span></div><p className="small-note">The coach uses this text. Check that the document was read correctly before publishing. Use # or ## before a heading to create a section.</p><textarea id="guidance-text" value={text} maxLength={240000} rows={12} onChange={e=>setText(e.target.value)} placeholder="Upload a file or paste your guidance here…" disabled={busy||extracting}/>
      <div className="editor-footer"><p>{editing?.status==="published"?"Changes to published text start a fresh walkthrough for learners.":"Saved as a draft. Publish from the library when you're ready."}</p><button className="primary" onClick={()=>void save()} disabled={busy||extracting||!title.trim()||text.trim().length<40}>{busy?<LoaderCircle size={17} className="spin"/>:<Check size={17}/>}Save {editing?"changes":"draft"}</button></div>
    </dialog>
    <dialog ref={confirmRef} className="confirm-dialog" onCancel={()=>{setDeleteTarget(null);setRestart(false);}}><h2>{deleteTarget?"Delete this guidance?":"Restart this walkthrough?"}</h2><p>{deleteTarget?`“${deleteTarget.title}” and its saved walkthroughs will be removed.`:"Your conversation and section progress for this guide will be cleared."}</p><div className="button-row"><button className="secondary" disabled={busy} onClick={()=>{setDeleteTarget(null);setRestart(false);}}>Cancel</button><button className={deleteTarget?"danger-button":"primary"} disabled={busy} onClick={()=>void confirmAction()}>{busy?"Working…":deleteTarget?"Delete guidance":"Restart walkthrough"}</button></div></dialog>
  </div>;
}
