import { useState,useEffect } from "react";
import { BookOpen, ShieldCheck, LoaderCircle, KeyRound } from "lucide-react";
import Workspace from "./components/Workspace";
type State={authenticated:boolean;admin:boolean;adminConfigured:boolean;learnerConfigured:boolean};
export default function App(){
  const [state,setState]=useState<State|null>(null),[role,setRole]=useState<"learner"|"admin">("learner"),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const refresh=async()=>{const r=await fetch("/api/auth/me");const data=await r.json() as State&{error?:string};if(!r.ok)throw new Error(data.error||"The workspace could not be opened.");setState(data);};
  useEffect(()=>{void refresh().catch(e=>setError(e.message));},[]);
  const login=async()=>{if(busy||!password)return;setBusy(true);setError("");try{const r=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({role,password})});const data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error||"Sign-in failed.");setPassword("");await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const logout=async()=>{if(busy)return;setBusy(true);setError("");try{const r=await fetch("/api/auth/logout",{method:"POST"});if(!r.ok)throw new Error("Could not sign out. Please try again.");setPassword("");await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  if(state?.authenticated)return <><Workspace onSignOut={()=>void logout()}/>{error&&<div className="logout-error" role="alert">{error}</div>}</>;
  return <div className="signin-page"><header className="topbar"><a className="brand" href="/"><span className="brand-mark"><BookOpen size={24}/></span><span>Guidance<span className="brand-light">Coach</span></span></a></header><main className="signin-main"><section className="signin-card"><span className="signin-icon">{role==="admin"?<ShieldCheck size={30}/>:<BookOpen size={30}/>}</span><p className="eyebrow">GUIDANCE COACH</p><h1>{role==="admin"?"Admin sign in":"Open your learning workspace"}</h1><p className="signin-intro">{role==="admin"?"Sign in to upload, review and publish guidance.":"Enter the access code from your administrator to work through your guidance."}</p><div className="signin-tabs" role="tablist" aria-label="Sign-in type"><button role="tab" aria-selected={role==="learner"} onClick={()=>{setRole("learner");setError("");setPassword("");}} disabled={busy}>Learner</button><button role="tab" aria-selected={role==="admin"} onClick={()=>{setRole("admin");setError("");setPassword("");}} disabled={busy}>Admin</button></div>
    {error&&<div className="alert error" role="alert">{error}</div>}
    {!state&&!error?<div className="thinking"><LoaderCircle className="spin" size={18}/>Opening the workspace…</div>:<form onSubmit={e=>{e.preventDefault();void login();}}><label className="field-label" htmlFor="access-password">{role==="admin"?"Admin password":"Learner access code"}</label><input id="access-password" type="password" value={password} maxLength={256} autoComplete="current-password" onChange={e=>setPassword(e.target.value)} disabled={busy} required/><button className="primary signin-submit" type="submit" disabled={busy||!password}>{busy?<LoaderCircle size={18} className="spin"/>:<KeyRound size={18}/>}Open workspace</button></form>}
    {state&&!(role==="admin"?state.adminConfigured:state.learnerConfigured)&&<p className="small-note">This workspace is waiting for its administrator to finish setup.</p>}
    <p className="signin-footer">Your guidance and coaching conversations are protected by sign-in.</p></section></main></div>;
}
